# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../gui/ui_selenium_window.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeleniumWindow(object):
    def setupUi(self, SeleniumWindow):
        SeleniumWindow.setObjectName("SeleniumWindow")
        SeleniumWindow.resize(323, 605)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SeleniumWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_ = QtWidgets.QHBoxLayout()
        self.horizontalLayout_.setObjectName("horizontalLayout_")
        self.start_chrome_btn = QtWidgets.QToolButton(SeleniumWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_chrome_btn.sizePolicy().hasHeightForWidth())
        self.start_chrome_btn.setSizePolicy(sizePolicy)
        self.start_chrome_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.start_chrome_btn.setObjectName("start_chrome_btn")
        self.horizontalLayout_.addWidget(self.start_chrome_btn)
        self.selenium_template_toolbtn = QtWidgets.QToolButton(SeleniumWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selenium_template_toolbtn.sizePolicy().hasHeightForWidth())
        self.selenium_template_toolbtn.setSizePolicy(sizePolicy)
        self.selenium_template_toolbtn.setMinimumSize(QtCore.QSize(75, 0))
        self.selenium_template_toolbtn.setObjectName("selenium_template_toolbtn")
        self.horizontalLayout_.addWidget(self.selenium_template_toolbtn)
        self.selenium_auto_record_toolbtn = QtWidgets.QToolButton(SeleniumWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selenium_auto_record_toolbtn.sizePolicy().hasHeightForWidth())
        self.selenium_auto_record_toolbtn.setSizePolicy(sizePolicy)
        self.selenium_auto_record_toolbtn.setMinimumSize(QtCore.QSize(75, 0))
        self.selenium_auto_record_toolbtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selenium_auto_record_toolbtn.setIconSize(QtCore.QSize(20, 20))
        self.selenium_auto_record_toolbtn.setObjectName("selenium_auto_record_toolbtn")
        self.horizontalLayout_.addWidget(self.selenium_auto_record_toolbtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_)
        self.scrollArea = QtWidgets.QScrollArea(SeleniumWindow)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 303, 559))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startWebBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startWebBtn.sizePolicy().hasHeightForWidth())
        self.startWebBtn.setSizePolicy(sizePolicy)
        self.startWebBtn.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/default/toolbutton/2_swipe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startWebBtn.setIcon(icon)
        self.startWebBtn.setIconSize(QtCore.QSize(30, 40))
        self.startWebBtn.setCheckable(True)
        self.startWebBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.startWebBtn.setAutoRaise(True)
        self.startWebBtn.setObjectName("startWebBtn")
        self.verticalLayout.addWidget(self.startWebBtn)
        self.touchBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touchBtn.sizePolicy().hasHeightForWidth())
        self.touchBtn.setSizePolicy(sizePolicy)
        self.touchBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.touchBtn.setIcon(icon)
        self.touchBtn.setIconSize(QtCore.QSize(30, 40))
        self.touchBtn.setCheckable(True)
        self.touchBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.touchBtn.setAutoRaise(True)
        self.touchBtn.setObjectName("touchBtn")
        self.verticalLayout.addWidget(self.touchBtn)
        self.airtestTouchBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airtestTouchBtn.sizePolicy().hasHeightForWidth())
        self.airtestTouchBtn.setSizePolicy(sizePolicy)
        self.airtestTouchBtn.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/default/toolbutton/1_touch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.airtestTouchBtn.setIcon(icon1)
        self.airtestTouchBtn.setIconSize(QtCore.QSize(30, 40))
        self.airtestTouchBtn.setCheckable(True)
        self.airtestTouchBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.airtestTouchBtn.setAutoRaise(True)
        self.airtestTouchBtn.setObjectName("airtestTouchBtn")
        self.verticalLayout.addWidget(self.airtestTouchBtn)
        self.textBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBtn.sizePolicy().hasHeightForWidth())
        self.textBtn.setSizePolicy(sizePolicy)
        self.textBtn.setMinimumSize(QtCore.QSize(0, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/default/toolbutton/5_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.textBtn.setIcon(icon2)
        self.textBtn.setIconSize(QtCore.QSize(30, 40))
        self.textBtn.setCheckable(True)
        self.textBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.textBtn.setAutoRaise(True)
        self.textBtn.setObjectName("textBtn")
        self.verticalLayout.addWidget(self.textBtn)
        self.assertBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assertBtn.sizePolicy().hasHeightForWidth())
        self.assertBtn.setSizePolicy(sizePolicy)
        self.assertBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.assertBtn.setIcon(icon1)
        self.assertBtn.setIconSize(QtCore.QSize(30, 40))
        self.assertBtn.setCheckable(True)
        self.assertBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.assertBtn.setAutoRaise(True)
        self.assertBtn.setObjectName("assertBtn")
        self.verticalLayout.addWidget(self.assertBtn)
        self.assertTemplateBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assertTemplateBtn.sizePolicy().hasHeightForWidth())
        self.assertTemplateBtn.setSizePolicy(sizePolicy)
        self.assertTemplateBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.assertTemplateBtn.setIcon(icon1)
        self.assertTemplateBtn.setIconSize(QtCore.QSize(30, 40))
        self.assertTemplateBtn.setCheckable(True)
        self.assertTemplateBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.assertTemplateBtn.setAutoRaise(True)
        self.assertTemplateBtn.setObjectName("assertTemplateBtn")
        self.verticalLayout.addWidget(self.assertTemplateBtn)
        self.snapshotBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotBtn.sizePolicy().hasHeightForWidth())
        self.snapshotBtn.setSizePolicy(sizePolicy)
        self.snapshotBtn.setMinimumSize(QtCore.QSize(0, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/default/toolbutton/13_snapshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotBtn.setIcon(icon3)
        self.snapshotBtn.setIconSize(QtCore.QSize(30, 40))
        self.snapshotBtn.setCheckable(True)
        self.snapshotBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.snapshotBtn.setAutoRaise(True)
        self.snapshotBtn.setObjectName("snapshotBtn")
        self.verticalLayout.addWidget(self.snapshotBtn)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.previousTabBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousTabBtn.sizePolicy().hasHeightForWidth())
        self.previousTabBtn.setSizePolicy(sizePolicy)
        self.previousTabBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.previousTabBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/default/toolbutton/4_exists.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousTabBtn.setIcon(icon4)
        self.previousTabBtn.setIconSize(QtCore.QSize(30, 39))
        self.previousTabBtn.setCheckable(True)
        self.previousTabBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.previousTabBtn.setAutoRaise(True)
        self.previousTabBtn.setObjectName("previousTabBtn")
        self.horizontalLayout_6.addWidget(self.previousTabBtn)
        self.newTabBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newTabBtn.sizePolicy().hasHeightForWidth())
        self.newTabBtn.setSizePolicy(sizePolicy)
        self.newTabBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.newTabBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.newTabBtn.setIcon(icon4)
        self.newTabBtn.setIconSize(QtCore.QSize(30, 39))
        self.newTabBtn.setCheckable(True)
        self.newTabBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.newTabBtn.setAutoRaise(True)
        self.newTabBtn.setObjectName("newTabBtn")
        self.horizontalLayout_6.addWidget(self.newTabBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.backBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.backBtn.setIcon(icon4)
        self.backBtn.setIconSize(QtCore.QSize(30, 39))
        self.backBtn.setCheckable(True)
        self.backBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.backBtn.setAutoRaise(True)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        self.forwardBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardBtn.sizePolicy().hasHeightForWidth())
        self.forwardBtn.setSizePolicy(sizePolicy)
        self.forwardBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.forwardBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.forwardBtn.setIcon(icon4)
        self.forwardBtn.setIconSize(QtCore.QSize(30, 39))
        self.forwardBtn.setCheckable(True)
        self.forwardBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.forwardBtn.setAutoRaise(True)
        self.forwardBtn.setObjectName("forwardBtn")
        self.horizontalLayout.addWidget(self.forwardBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(SeleniumWindow)
        QtCore.QMetaObject.connectSlotsByName(SeleniumWindow)

    def retranslateUi(self, SeleniumWindow):
        _translate = QtCore.QCoreApplication.translate
        SeleniumWindow.setWindowTitle(_translate("SeleniumWindow", "Form"))
        self.start_chrome_btn.setText(_translate("SeleniumWindow", "..."))
        self.selenium_template_toolbtn.setText(_translate("SeleniumWindow", "..."))
        self.selenium_auto_record_toolbtn.setText(_translate("SeleniumWindow", "..."))
        self.startWebBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>get(web)</p><p>@param web: the url of test web.</p></body></html>"))
        self.startWebBtn.setStatusTip(_translate("SeleniumWindow", "start_web()"))
        self.startWebBtn.setText(_translate("SeleniumWindow", "start_web"))
        self.touchBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>click()</p><p>Click the selected element.</p></body></html>"))
        self.touchBtn.setStatusTip(_translate("SeleniumWindow", "touch()"))
        self.touchBtn.setText(_translate("SeleniumWindow", "touch"))
        self.airtestTouchBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>airtest_touch(v)</p><p>@param v: Templation that to touch.</p></body></html>"))
        self.airtestTouchBtn.setStatusTip(_translate("SeleniumWindow", "airtest_touch()"))
        self.airtestTouchBtn.setText(_translate("SeleniumWindow", "airtest_touch"))
        self.textBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>send_keys(text, keyboard)</p><p>@param text: The text will input to the selected element.</p><p>@param keyboard: The event with keyboard after text input.(like Keys.ENTER)</p></body></html>"))
        self.textBtn.setStatusTip(_translate("SeleniumWindow", "text()"))
        self.textBtn.setText(_translate("SeleniumWindow", "text"))
        self.assertBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>assert()</p><p>Assert exist element.</p></body></html>"))
        self.assertBtn.setStatusTip(_translate("SeleniumWindow", "assert()"))
        self.assertBtn.setText(_translate("SeleniumWindow", "assert"))
        self.assertTemplateBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>assert_template(v)</p><p>@param v: Templation.</p></body></html>"))
        self.assertTemplateBtn.setStatusTip(_translate("SeleniumWindow", "assert_template()"))
        self.assertTemplateBtn.setText(_translate("SeleniumWindow", "assert_template"))
        self.snapshotBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>snapshot(file)</p><p>Save a current web page to a image file, we can verify current web page in HTML report.</p><p>@param file: The path of save snapshot.</p></body></html>"))
        self.snapshotBtn.setStatusTip(_translate("SeleniumWindow", "snapshot()"))
        self.snapshotBtn.setText(_translate("SeleniumWindow", "snapshot"))
        self.previousTabBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>switch_to_previous_tab()</p><p>Switch to the father tab of current tab.</p></body></html>"))
        self.previousTabBtn.setStatusTip(_translate("SeleniumWindow", "previous_tab()"))
        self.previousTabBtn.setText(_translate("SeleniumWindow", "previous_tab"))
        self.newTabBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>switch_to_new_tab()</p><p>Switch to the new tab.</p></body></html>"))
        self.newTabBtn.setStatusTip(_translate("SeleniumWindow", "new_tab()"))
        self.newTabBtn.setText(_translate("SeleniumWindow", "new_tab"))
        self.backBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>back()</p><p>Back to last page.</p></body></html>"))
        self.backBtn.setStatusTip(_translate("SeleniumWindow", "back()"))
        self.backBtn.setText(_translate("SeleniumWindow", "back"))
        self.forwardBtn.setToolTip(_translate("SeleniumWindow", "<html><head/><body><p>forward()</p><p>Forward to next page.</p></body></html>"))
        self.forwardBtn.setStatusTip(_translate("SeleniumWindow", "forward()"))
        self.forwardBtn.setText(_translate("SeleniumWindow", "forward"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SeleniumWindow = QtWidgets.QWidget()
    ui = Ui_SeleniumWindow()
    ui.setupUi(SeleniumWindow)
    SeleniumWindow.show()
    sys.exit(app.exec_())

