#!/usr/bin/python3
# -*- coding: utf-8 -*-
from enum import Enum


class GlobalType(Enum):
	ITEM = 0
	GEM = 1
	RESOURCE = 2
	TROOP = 3
	LORD_EXP = 4
	RESEARCH_LEVEL = 8
	LORD_LEVEL = 9
	ALLIANCE_GIFT = 10
	VIP_POINT = 11
	VIP_LEVEL = 14
	DEFENCE = 16
	SPEED_TIME = 19
	SPEED_PERCENT = 20
	EQUIP = 23
	CRYSTAL = 24
	MATERIAL = 25
	ALLIANCE_LOYALTY = 27
	BUILDING_LEVEL = 31
	EQUIP_SOUL = 32
	EQUIP_PARTS = 33
	DRAGON_ENERGY = 34
	REGISTER_TIME = 39
	DRAGON_EXP = 44
	DRAGON_LEVEL = 45
	LORD_HEAD = 54
	EQUIP_SOUL_TYPE = 56
	EQUIP_PARTS_TYPE = 57
	HERO_EXP = 58
	LORD_ENERGY = 59
	HERO = 60
	OTHER = 100


class ActionType(Enum):
	BUILD_UPGRADE = 1
	BUILD_REMOVE = 2
	
	RESEARCH_UPGRADE = 3
	
	TROOP_TRAIN = 4
	TROOP_HEAL = 6
	
	FORT_TRAIN = 5
	FORT_REPAIR = 19
	
	EQUIP_UPGRADE = 18
	
	REMOVE_OBSTACLE = 20
	
	TRANSPORT = 8
	REINFORCE = 9
	SCOUT = 10
	ITEM = 11
	ATTACK = 12
	OCCUPY = 13
	CAMP = 17
	DRAGON_ATTACK = 22
	DRAGON_OCCUPY = 23
	RALLY_WAR = 24
	RALLY_REINFORCE = 25
	
	RANDOM_MOVE_CITY = 21
	
	THRONE_DONATE = 35
	ESCORT_DRAGON = 37
	RELEASE_DRAGON = 38
	
	ATTACK_THRONE = 39
	RALLY_WAR_THRONE = 40
	REINFORCE_THRONE = 41
	DISPATCH_THRONE = 42
	ATTACK_IDOL = 43
	KVK_MOVE = 49
	
	ATTACK_SUPER_THRONE = 51
	RALLY_WAR_SUPER_THRONE = 52
	REINFORCE_SUPER_THRONE = 53
	DISPATCH_SUPER_THRONE = 54
	ATTACK_BANDIT = 60
